### ISSUE TITLE
Is uncle used?

### ISSUE THREAD

**Issue by ralphtheninja** [datrs/flat-tree#12]
I noticed that `uncle` was implemented, which isn't part of the js api. Is that used somewhere?

**Comment by yoshuawuyts** [comment]
It's not afaik, but having it in there can probably be useful sometimes. Dead code elimination strips it for us at compile time ✨

**Comment by ralphtheninja** [comment]
Maybe I should explain why I made this issue in the first place. Things that "might be useful sometimes" to me are bad since they add more things to think about. I think there are functions in `mafintosh/flat-tree` that aren't used either, so when porting that lib to other languages (e.g. this lib), functions are being re-implemented which shouldn't need to be re-implemented.
