### ISSUE TITLE
consider removing xyz_with_depth() from the api?

### ISSUE THREAD

**Issue by ralphtheninja** [datrs/flat-tree#14]
I have an index, lets say `index = 44` and I want the offset, so I call `offset(44)`. Does it even make sense to call `offset_with_depth(44, 4)`?

I suspect these functions are there because rust doesn't have default values for function parameters, which is the same thing for functions in c.

Maybe all `xyz_with_depth()` should be local only?

Same goes for `.sibling()`, `.parent()` etc

More concretely, does a calling lib ever pass in `depth` explicitly?

**Comment by ralphtheninja** [comment]
It's completely possible that I'm missing something, please excuse my ignorance in that case :wink:

**Comment by yoshuawuyts** [comment]
> Maybe all xyz_with_depth() should be local only?

Possibly! I haven't seen it being used yet anywhere outside of this  codebase yet, so I'm thinking it might indeed need to be private.

Perhaps we should make a little more progress on hypercore to check if it's indeed all private, and if it is we patch it here?

Really good catch!

**Comment by ralphtheninja** [comment]
> Perhaps we should make a little more progress on hypercore to check if it's indeed all private, and if it is we patch it here?

Def! :heart:

**Comment by yoshuawuyts** [comment]
bad news https://github.com/mafintosh/hypercore/blob/master/lib/tree-index.js#L123

**Comment by ralphtheninja** [comment]
Aaah ok. Maybe we can push those algorithms down to `flat-tree` instead? Just thinking out loud.

**Comment by ralphtheninja** [comment]
I'll make a list here on the functions that do require using `depth`:

* `flat.parent()`
* `flat.index()`
* `flat.offset()`
* `flat.leftChild()`

**Comment by yoshuawuyts** [comment]
@ralphtheninja will do!
