### ISSUE TITLE
error[E0554]: #![feature] may not be used on the stable release channel

### ISSUE THREAD

**Issue by prettymuchbryce** [datrs/flat-tree#32]
When compiling [hypercore](https://github.com/datrs/hypercore) I get the following error:

```
error[E0554]: #![feature] may not be used on the stable release channel
 --> /Users/bryce/.cargo/registry/src/github.com-1ecc6299db9ec823/flat-tree-3.3.0/src/lib.rs:2:1
  |
2 | #![feature(external_doc)]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^
```

```
cargo --version
cargo 1.28.0 (96a2c7d16 2018-07-13)
```

I'm not very familiar with Rust, is it implied that I should not be using the stable release channel?

**Comment by yoshuawuyts** [comment]
Oh yeah, you're entirely right. We should put that behind a `#[cfg_attr(feature = "nightly", feature(external_doc))]` flag ([example](https://github.com/datrs/random-access-memory/blob/master/src/lib.rs#L1-L4)). Would you want to submit a patch to fix that?

**Comment by prettymuchbryce** [comment]
@yoshuawuyts Thank you for clarifying.

I have opened a PR as you suggested here: https://github.com/datrs/flat-tree/pull/33
